<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.1.3 (Python 3.10.5 on win32)" generated="20230315 19:07:52.610" rpa="false" schemaversion="2">
<suite id="s1" name="Saucedemo3" source="D:\robotframework\saucedemo3.robot">
<kw name="Open Browser" library="SeleniumLibrary" type="SETUP">
<arg>${webURL}</arg>
<arg>${BROWSERS}</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<msg timestamp="20230315 19:07:52.799" level="INFO">Opening browser 'Chrome' to base url 'https://www.saucedemo.com/'.</msg>
<status status="PASS" starttime="20230315 19:07:52.798" endtime="20230315 19:07:55.354"/>
</kw>
<test id="s1-t1" name="Login with invalid username user in the CSV file">
<kw name="I login with invalid username and invalid password">
<arg>${username}</arg>
<arg>${password}</arg>
<msg timestamp="20230315 19:07:55.358" level="FAIL">Variable '${username}' not found.</msg>
<status status="FAIL" starttime="20230315 19:07:55.357" endtime="20230315 19:07:55.359"/>
</kw>
<status status="FAIL" starttime="20230315 19:07:55.355" endtime="20230315 19:07:55.359">Variable '${username}' not found.</status>
</test>
<kw name="Close Browser" library="SeleniumLibrary" type="TEARDOWN">
<doc>Closes the current browser.</doc>
<status status="PASS" starttime="20230315 19:07:55.361" endtime="20230315 19:07:57.585"/>
</kw>
<status status="FAIL" starttime="20230315 19:07:52.612" endtime="20230315 19:07:57.585"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Saucedemo3">Saucedemo3</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20230315 19:07:52.794" level="ERROR">[ DataDriver ] Error in robot file:
  File "D:\robotframework\saucedemo3.robot", line 0</msg>
<msg timestamp="20230315 19:07:52.795" level="ERROR">In source file:
  File "../Resources/credentials.csv", line 0</msg>
<msg timestamp="20230315 19:07:52.797" level="ERROR">Calling method '_start_suite' of listener 'DataDriver' failed: FileNotFoundError: File attribute was not a full path. Tried to find D:\robotframework\../Resources/credentials.csv but file does not exist.</msg>
</errors>
</robot>
